### ISSUE TITLE
Sorting by Github stars is broken after opting out of Github integration

### ISSUE THREAD

**Issue by wasamasa** [Malabarba/paradox#85] opened 2015-07-30 08:08 UTC
I was curious whether the Github stars column in the header line does work at all, given that no such column is present in the data, so I've clicked it and got the following:

![](http://i.imgur.com/SqM5CFn.png)

```
apply: Args out of range: [("ace-window" face link follow-link t package-desc [cl-struct-package-desc ace-window (0 9 0) "Quickly switch windows." ((avy (0 2 0))) single "gnu" nil ((:url . "https://github.com/abo-abo/ace-window") (:keywords "window" "location")) nil] action package-menu-describe-package) #("0.9.0" 0 5 (font-lock-face default)) #("available" 0 9 (font-lock-face default)) #("Quickly switch windows." 0 23 (font-lock-face default))], 4
```

See also #84.

**Comment by Malabarba** [comment] 2015-07-31 11:07
Yes, whatever issue is causing #84 is certainly the cause for this one too. You should still be seeting the number of stars in the buffer (amongst other things that are also missing). So I'll just close this as duplicate of that.

**Closed by Malabarba** 2015-07-31 11:07 UTC
